language: ruby
rvm:
- 2.2
before_script:
- chmod a+x ./scripts/build.sh
- chmod a+x ./scripts/deploy.sh
script:
- "./scripts/build.sh"
deploy:
  provider: script
  script: "./scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/positive-js/blog.git
  - REPO_TARGET_BRANCH: gh-pages
  - secure: j0+a2SnXywaUawYUx2lgxAtRobQ2pcjvloOT0YqP6b/QKsthV2sbgiqzyJ4Uah6TO3Pf35Gh+7p3Hr74m0LuHa0yMcxgomm7hwtGF+sIqDWReWPGb08matV8MvDNHAIc1S4eXcxcCHXUjioEpAear0TeAfEXPbsuVXmiRmddW12C7Lng3ido1wPASSupjnnauUJEfy7wr0DgmWp7F6VqHx4HTgdhzBm3EdVLPaesx2SOKsQHN3j2o6A5vWTvtOC7m+bou5xb/riiy543CzUFVHPVchN5xqFf3yvS4tL2Zl0KKGrViptDN9kBbFAHSuWrPdR0SA5T+bKJHuoa65ebCa21fWYzZT0jvBSIeM7csGoNd5cKuSpTaG1nlLFCUjlpNoF6Xmb6GYp4KWOi952UuooeuXLMoHh2ze3LSwWPemI4J5KxW7+eNz5x+6VKdt3cmPKokmnPjeFg+vhOuufzQfpDeYD/jkC9p0MMmT3Pi147m1L+pjaHZ+xcAn6rwlmrzMIiUJAaVBtzSVvZdgLeO9FHU9xnwSA8W1yhxYwy/p3BfHTVJo8u9nX6s/2+d0iL1bXktvi3yTwhCIRlGlLivlRYWqobxknCA71NkI7trtfmF26GPoOBv6QGPt7obK/cT2ykTHhnExHVOtuP9KLqqOOYrxmRHe3FsL4cl7ZdBso=
  - secure: BZlAhtCvenRboKWMQf+Wec6vFekxBgQAYZ75+Cc2vK/T8E0yXXqenmpv+8eeegluOtNLb4C2DOqQuXLx13ONWmNkNJt2LEqp9v/TYxEySyXAVD6B2EDio5+vjnesbs9v95rB+UZfLdm5vrbRcciNXhCbu6Y4rt5IEjC6X51he/PMNNZsUoRNNCubLwnUGe1R/2uSBbjlPOJg3kqA3/FC3oOm74nrDLXudqWwRpdWqiW5VlW6LXQX2NpKmHLgrxpSnXSccH93okwEZTdVOR9aB9l6kx8d2qguxv9uagiRvDFgvHGihk8fEPUtYo92vx4CADyx6+aneOJaEWxgZa9VvtNA5tp6woyQeN4KCI0n7N3M3DkDI0UKHIp8VRc1c0ySAX8zEBMj4pknKILYzT4cop7QS6SO7c1uNULVS5uWfCVI+ah+FPjXt5emuQ3dF7gbIl+dPschduVDYdIxmo5BEw51qjmg6mCgc2O+Ix3mPgbC2gDQA6PrLaP3bQ52Bl29nIQiASHeyvfQa4ukeiOkCHIJot6nw/1nNlJDbFIPi8lIuQMtGtuoKElW5mNlRx5aujHwplVR6CWn6JrGYQhRj2v5cLH3JtYKBdalHuAUuVyAuQd38j/W/PtlIsWCRdCK7x0nqITtawCUexST0PBapj0nWN49QHdnurwPWnh3QJo=
